AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: TaskFlow Serverless Task Manager Backend

Globals:
  Function:
    Runtime: python3.12
    Timeout: 30
    MemorySize: 256

Resources:
  
  # ---------------- COGNITO USER POOL ----------------
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: taskflow-userpool
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
  
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      ClientName: taskflow-frontend
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthFlows:
        - code
        - implicit
      AllowedOAuthScopes:
        - openid
        - email
        - profile
      CallbackURLs:
        - http://localhost:3000/dashboard
      LogoutURLs:
        - http://localhost:3000/
      SupportedIdentityProviders:
        - COGNITO


  # ---------------- HTTP API (v2) ----------------
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        AllowOrigins:
          - "*"
        AllowHeaders:
          - "*"
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            AuthorizationType: JWT
            IdentitySource: "$request.header.Authorization"
            JwtConfiguration:
              issuer: !Sub "https://cognito-idp.${AWS::Region}.amazonaws.com/${UserPool}"
              audience:
                - !Ref UserPoolClient     

  # ---------------- CREATE TASK ----------------
  CreateTaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/create_task/
      Handler: app.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TasksTable
      Events:
        CreateTask:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /tasks
            Method: POST

  # ---------------- LIST TASKS ----------------
  ListTasksFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/list_tasks/
      Handler: app.lambda_handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref TasksTable
      Events:
        ListTasks:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /tasks
            Method: GET

  # ---------------- UPDATE TASK ----------------
  UpdateTaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/update_task/
      Handler: app.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TasksTable
      Events:
        UpdateTask:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /tasks/{taskId}
            Method: PUT

  # ---------------- DELETE TASK ----------------
  DeleteTaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/delete_task/
      Handler: app.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TasksTable
      Events:
        DeleteTask:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /tasks/{taskId}
            Method: DELETE
            
  # ---------------- DYNAMODB TABLE ----------------
  TasksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: task-manager
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

Outputs:
  ApiUrl:
    Description: "HTTP API endpoint URL"
    Value: !Sub "${HttpApi.ApiEndpoint}"